name: CI Pull Request

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  LIB_ID: MyAwesomeLib

jobs:
  # lint:
  #   name: Lint Check
  #   runs-on: ubuntu-latest

  #   container:
  #     image: valalang/lint

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Lint
  #     run: io.elementary.vala-lint -d .

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    # needs: lint

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Replace patterns
      run: sh test-template.sh ${{ env.LIB_ID }}
